apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testparallel.fullname" . }}
  labels:
    {{- include "testparallel.labels" . | nindent 4 }}
data:
  config.json: {{- .Values.config | toJson | quote | nindent 4 }}
