apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testparallel.fullname" . }}-historical-common
  labels:
    {{- include "testparallel.labels" . | nindent 4 }}
data:
  config.json: {{- .Values.configHistorical | toJson | quote | nindent 4 }}
