{{- if .Values.pdb.enabled }}

{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "testparallel.fullname" . }}
  labels:
    {{- include "testparallel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "testparallel.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.pdb.maxUnavailable ( not .Values.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- end }}

{{- end }}
